import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "module";
import fs from "fs";
import path from "path";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");
const skipDeploy = process.env.MVN_SKIP_DEPLOY === "1";

// Copy build output to local vault plugin folders listed in deploy-targets.json
// (gitignored; see deploy-targets.example.json). Absent file = build only.
const deployConfigFile = "deploy-targets.json";
let deployTargets = [];
if (!skipDeploy && fs.existsSync(deployConfigFile)) {
	try {
		const parsed = JSON.parse(fs.readFileSync(deployConfigFile, "utf8"));
		if (Array.isArray(parsed) && parsed.every(t => typeof t === "string")) {
			deployTargets = parsed;
		} else {
			console.error(`${deployConfigFile} must be a JSON array of strings; ignoring.`);
		}
	} catch (e) {
		console.error(`Could not parse ${deployConfigFile}:`, e);
	}
}

function copyToTargets() {
	if (skipDeploy) {
		console.log("Skipping local deployment because MVN_SKIP_DEPLOY=1");
		return;
	}
	for (const dir of deployTargets) {
		try {
			fs.mkdirSync(dir, { recursive: true });
			for (const file of ["main.js", "manifest.json", "styles.css"]) {
				fs.copyFileSync(file, path.join(dir, file));
			}
			console.log(`Copied build to ${dir}`);
		} catch (e) {
			console.error(`Copy to ${dir} failed:`, e);
		}
	}
}

const copyPlugin = {
	name: "copy-to-vaults",
	setup(build) {
		build.onEnd(result => {
			if (result.errors.length === 0) copyToTargets();
		});
	}
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2022",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	plugins: [copyPlugin],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
